# Generated by Django 2.1.7 on 2019-03-03 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_expenses',
            name='date_spent',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='general_expenses',
            name='category',
            field=models.IntegerField(choices=[(1, 'Food'), (2, 'Travel'), (3, 'Groceries'), (4, 'Electronics'), (5, 'Clothing or Footwear'), (6, 'Household shopping'), (7, 'Other- specify in remarks')]),
        ),
        migrations.AlterField(
            model_name='mandatory_expenses',
            name='category',
            field=models.IntegerField(choices=[(1, 'Food'), (2, 'Travel'), (3, 'Groceries'), (4, 'Electronics'), (5, 'Clothing or Footwear'), (6, 'Household shopping'), (7, 'Other- specify in remarks')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
